baseURL = "https://yassine-rejeb.github.io/Yassine-Rejeb/"
relativeURLs = true
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Mohamed Yassine Rejeb"

# theme as hugo module
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

# Add indexing for search engines
# Needs Hugo version 0.60.0 or higher
# https://gohugo.io/getting-started/configuration-markup#enableEmoji


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
